version: '3'

services:
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    command: redis-server --appendonly yes

volumes:
  cache:
    driver: local
